docs_dir: 
site_dir: 
site_name: My Docs
site_url: https://codush.github.io/template_app_pages/
theme: material
nav:
    - 'Home Page': home.md
    - 'About Page': about.md
    - Nested: 
        - 'A nested Home Page' : 'nested/nested_home.md'
        - 'A nested About Page' : 'nested/nested_about.md'
copyright: 'codush 2022'